apiVersion: v1
kind: Service
metadata:
  name: rest-server-svc
  namespace: {{ .Release.Name }}-{{ .Values.global.namespace }}
spec:
  selector:
    app: rest-server
    version: "1.0"
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
