apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Name }}-{{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    version: "{{ .Chart.AppVersion }}"
  # type: NodePort
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      # nodePort: 30500
