apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  namespace: {{ .Release.Name }}-{{ .Values.global.namespace }}
spec:
  selector:
    app: zipkin
    version: "1.0"
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30600