apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-depl
  labels:
    app: zipkin
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
      version: "1.0"
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
        version: "1.0"
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim
          ports:
          - containerPort: 9411