# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'gRpc.Vs.WebApi.Gateway/gRpc.Vs.WebApi.Gateway.csproj'
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'gRpc.Vs.WebApi.Gateway/gRpc.Vs.WebApi.Gateway.csproj'
    publishWebProjects: false
    zipAfterPublish: false
    arguments: '-c $(BuildConfiguration) -o out'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'out'
#     ArtifactName: 'gateway'
#     publishLocation: 'Container'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'gRpc.Vs.WebApi.Gateway/gRpc.Vs.WebApi.Gateway.csproj'
    packDirectory: 'out'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'
- task: NuGetAuthenticate@0
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'out/**/*.nupkg;!out/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd4d86f1e-60c1-4453-b712-9d05fcc2a0c5'



