version: '3'
services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile.gateway
    image: dzejsien/grpc/gateway
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - e:/https:/https/
    environment: 
      ENV ASPNETCORE_URLS: "https://+;http://+"
      ENV ASPNETCORE_HTTPS_PORT: 5001
      ENV ASPNETCORE_Kestrel__Certificates__Default__Password: "12345"
      ENV ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ENV "Urls:RestServer": "http://rest-server2/"
    
     
    
